/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as BioRouteImport } from './routes/bio'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCreateCheckoutRouteImport } from './routes/api/create-checkout'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateCheckoutRoute = ApiCreateCheckoutRouteImport.update({
  id: '/api/create-checkout',
  path: '/api/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/bio': typeof BioRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/engagement': typeof EngagementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/programme': typeof ProgrammeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/bio': typeof BioRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/engagement': typeof EngagementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/programme': typeof ProgrammeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/bio': typeof BioRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/engagement': typeof EngagementRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/programme': typeof ProgrammeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/bio'
    | '/confidentialite'
    | '/engagement'
    | '/mentions-legales'
    | '/programme'
    | '/sitemap.xml'
    | '/api/create-checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/bio'
    | '/confidentialite'
    | '/engagement'
    | '/mentions-legales'
    | '/programme'
    | '/sitemap.xml'
    | '/api/create-checkout'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/bio'
    | '/confidentialite'
    | '/engagement'
    | '/mentions-legales'
    | '/programme'
    | '/sitemap.xml'
    | '/api/create-checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  BioRoute: typeof BioRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  EngagementRoute: typeof EngagementRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ProgrammeRoute: typeof ProgrammeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCreateCheckoutRoute: typeof ApiCreateCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-checkout': {
      id: '/api/create-checkout'
      path: '/api/create-checkout'
      fullPath: '/api/create-checkout'
      preLoaderRoute: typeof ApiCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  BioRoute: BioRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  EngagementRoute: EngagementRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ProgrammeRoute: ProgrammeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCreateCheckoutRoute: ApiCreateCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
